export default {
    CADASTRAR_AUTORES: "/cadastrarAutores",
    LISTAR_TODOS_AUTORES: "/listarTodosAutores",
    BUSCAR_AUTOR_POR_ID: "/buscarPorId/{id}",
    BUSCAR_AUTOR_POR_NOME: "/buscarPorNome/{nome}",
    EDITAR_AUTOR: "/editarAutor/{id}",
    DELETAR_AUTOR: "/deletarAutor/{id}",
    LISTAR_CATEGORIAS: "/listarCategorias",
    CRIAR_CATEGORIAS: "/criarCategorias",
    INATIVAR_CATEGORIA: "/inativar/{id}",
    ATIVAR_CATEGORIA: "/ativar/{id}/",
    BUSCAR_CATEGORIA_POR_NOME: "/buscarCategoria/{nome}",
    CADASTRAR_CLIENTES: "/cadastrarClientes",
    DELETAR_CLIENTE: "/deletarCliente/{id}",
    LISTAR_CLIENTES: "/listarClientes",
    BUSCAR_CLIENTE_POR_ID: "/buscarClientesId/{id}",
    CADASTRAR_EDITORA: "/cadastrarEditora",
    DELETAR_EDITORA: "/DeletarEditora/{id}",
    LISTAR_EDITORAS: "/listarEditoras",
    BUSCAR_EDITORA_POR_NOME: "/buscarPeloNome/{nome}",
    BUSCAR_EDITORA_POR_ID: "/buscarEditoraPorId/{id}",
    EDITAR_EDITORA: "/editarEditoras/{id}",
    CADASTRAR_LIVROS: "/cadastrarLivros",
    LISTAR_LIVROS: "/listarLivros",
    BUSCAR_LIVRO_POR_ID: "/buscarLivroPorId/{id}",
    BUSCAR_LIVRO_POR_TITULO: "/buscarPorTitulo/{titulo}",
};
